#!/usr/bin/env bash
#Implementing a 301 redirect
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
