#!/usr/bin/env bash
#Implementing a 301 redirect and custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

config=\
"server {
	listen 80 default_server;
        listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

	error_page 404 /custom_404.html;
	location = /custom_404.html {
	internal;
	}

	location /redirect_me {
		rewrite ^ https://youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
echo "$config" > /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
