#!/usr/bin/env bash
#Implementing a 301 redirect and custom 404 page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo service nginx start

sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo service nginx restart
