#!/usr/bin/env bash
#Implementing a 301 redirect and custom 404 page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html


sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default


echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

sed -i '/listen [::]:80 default_server;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo service nginx restart
