#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original


sudo bash -c 'cat <<EOF | tee -a /etc/haproxy/haproxy.cfg
frontend lb-01
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 531594-web-01 52.91.118.63 check
    server 531594-web-02 54.175.17.114 check
EOF'

sudo service haproxy start
