#!/usr/bin/env bash
#generates a MySQL dump and creates a compressed archive out of it.

d=$(date +"%d")
m=$(date +"%m")
y=$(date +"%Y")
file="$d-$m-$y.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file" backup.sql
