#!/usr/bin/env bash
# This script is to display numbers 1-100 implementing the FizzBuzz criteria
i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
