#!/usr/bin/env bash
# Displays different output on 4th & 8th iteration, uses while loop
i="1"
while [ $i -le 10 ]
do
        if [ $i -eq 4 ]
        then
                echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
        else
                echo "Hi"
        fi
        ((i++))
done
