#!/usr/bin/env bash
#Configures an ubuntu server for the localhost to 127.0.0.2 and facebook.com to 8.8.8.8.


sudo sed -i s/127.0.0.1/127.0.0.2/ /etc/hosts
echo "8.8.8.8   facebook.com" >> /etc/hosts
