#!/usr/bin/env bash
#efficient implementation of 1-run_nginx_as_nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
